CREATE TABLE save_search_criteria(

	user_id varchar(15) not null,
	save_search_title varchar(400) not null,
	geographic_area_name_1 varchar(100),
	geographic_area_name_2 varchar(100),
	geographic_area_name_3 varchar(100),
	geographic_area_name_4 varchar(100),
	geographic_area_name_5 varchar(100),
	geographic_area_name_6 varchar(100),
	geographic_area_name_7 varchar(100),
	geographic_area_name_8 varchar(100),
	geographic_area_name_9 varchar(100),
	geographic_area_name_10 varchar(100),
	use_case_name_1 varchar(60),
	use_case_name_2 varchar(60),
	use_case_name_3 varchar(60),
	use_case_name_4 varchar(60),
	use_case_name_5 varchar(60),
	use_case_name_6 varchar(60),
	use_case_name_7 varchar(60),
	use_case_name_8 varchar(60),
	use_case_name_9 varchar(60),
	use_case_name_10 varchar(60),
	creation_date timestamp default CURRENT_TIMESTAMP,
	updation_date timestamp default CURRENT_TIMESTAMP,
	active_status boolean default 'true',
	created_on timestamp not null default CURRENT_TIMESTAMP,
	created_by integer default 1,
	updated_on timestamp not null default CURRENT_TIMESTAMP,
	updated_by integer default 1
)