-- DROP TABLE IF EXISTS public.save_search_criteria;

CREATE TABLE IF NOT EXISTS public.save_search_criteria
(
    user_id character varying(15) COLLATE pg_catalog."default" NOT NULL,
    save_search_title character varying(400) COLLATE pg_catalog."default" NOT NULL,
    geographic_area_name_1 character varying(100) COLLATE pg_catalog."default",
    geographic_area_name_2 character varying(100) COLLATE pg_catalog."default",
    geographic_area_name_3 character varying(100) COLLATE pg_catalog."default",
    geographic_area_name_4 character varying(100) COLLATE pg_catalog."default",
    geographic_area_name_5 character varying(100) COLLATE pg_catalog."default",
    geographic_area_name_6 character varying(100) COLLATE pg_catalog."default",
    geographic_area_name_7 character varying(100) COLLATE pg_catalog."default",
    geographic_area_name_8 character varying(100) COLLATE pg_catalog."default",
    geographic_area_name_9 character varying(100) COLLATE pg_catalog."default",
    geographic_area_name_10 character varying(100) COLLATE pg_catalog."default",
    use_case_name_1 character varying(60) COLLATE pg_catalog."default",
    use_case_name_2 character varying(60) COLLATE pg_catalog."default",
    use_case_name_3 character varying(60) COLLATE pg_catalog."default",
    use_case_name_4 character varying(60) COLLATE pg_catalog."default",
    use_case_name_5 character varying(60) COLLATE pg_catalog."default",
    use_case_name_6 character varying(60) COLLATE pg_catalog."default",
    use_case_name_7 character varying(60) COLLATE pg_catalog."default",
    use_case_name_8 character varying(60) COLLATE pg_catalog."default",
    use_case_name_9 character varying(60) COLLATE pg_catalog."default",
    use_case_name_10 character varying(60) COLLATE pg_catalog."default",
    creation_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updation_date timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    active_status boolean DEFAULT true,
    created_on timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by integer DEFAULT 1,
    updated_on timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by integer DEFAULT 1,
    geo_id_1 character varying(50) COLLATE pg_catalog."default",
    geo_id_2 character varying(50) COLLATE pg_catalog."default",
    geo_id_3 character varying(50) COLLATE pg_catalog."default",
    geo_id_4 character varying(50) COLLATE pg_catalog."default",
    geo_id_5 character varying(50) COLLATE pg_catalog."default",
    geo_id_6 character varying(50) COLLATE pg_catalog."default",
    geo_id_7 character varying(50) COLLATE pg_catalog."default",
    geo_id_8 character varying(50) COLLATE pg_catalog."default",
    geo_id_9 character varying(50) COLLATE pg_catalog."default",
    geo_id_10 character varying(50) COLLATE pg_catalog."default",
    use_case_group_1 character varying(12) COLLATE pg_catalog."default",
    use_case_group_2 character varying(12) COLLATE pg_catalog."default",
    use_case_group_3 character varying(12) COLLATE pg_catalog."default",
    use_case_group_4 character varying(12) COLLATE pg_catalog."default",
    use_case_group_5 character varying(12) COLLATE pg_catalog."default",
    use_case_group_6 character varying(12) COLLATE pg_catalog."default",
    use_case_group_7 character varying(12) COLLATE pg_catalog."default",
    use_case_group_8 character varying(12) COLLATE pg_catalog."default",
    use_case_group_9 character varying(12) COLLATE pg_catalog."default",
    use_case_group_10 character varying(12) COLLATE pg_catalog."default",
    save_search_id integer NOT NULL DEFAULT nextval('save_search_criteria_save_search_id_seq'::regclass),
    use_case_color_1 character varying(7) COLLATE pg_catalog."default",
    use_case_color_2 character varying(7) COLLATE pg_catalog."default",
    use_case_color_3 character varying(7) COLLATE pg_catalog."default",
    use_case_color_4 character varying(7) COLLATE pg_catalog."default",
    use_case_color_5 character varying(7) COLLATE pg_catalog."default",
    use_case_color_6 character varying(7) COLLATE pg_catalog."default",
    use_case_color_7 character varying(7) COLLATE pg_catalog."default",
    use_case_color_8 character varying(7) COLLATE pg_catalog."default",
    use_case_color_9 character varying(7) COLLATE pg_catalog."default",
    use_case_color_10 character varying(7) COLLATE pg_catalog."default",
    user_type character varying(20) COLLATE pg_catalog."default" DEFAULT USER,
    CONSTRAINT save_search_criteria_pkey PRIMARY KEY (user_id, save_search_title)
)